spring:
  application:
    name: backend-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop
      show-sql: true
    h2:
      console:
        enabled: true
        path: /h2-console

external:
  api:
    users-url: ${API_URL}

springdoc:
  api-docs:
    path: /swagger-ui.html